site_name: xDrip+

theme:
    name: material
    language: en
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - navigation.top
        - search.suggest
        - search.highlight
        - content.code.annotate
    logo: xDrip+logo.png
    favicon: xDrip+logo.png
    palette:
      primary: white
      scheme: default
    nav_style: primary

extra_css:
    - css/admonitions.css

markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁
        
nav:
    - Getting started:
        - 'Prerequisites': 'install/prerequisites.md'
        - 'Download': 'install/download.md'
        - 'Installation': 'install/install.md'
        - 'Data source': 'install/datasource.md'
        - 'G4': 'install/g4.md'
        - 'G5': 'install/g5.md'
        - 'G6': 'install/g6.md'
    - Troubleshooting:
        - 'Installation': 'troubleshoot/install.md'