site_name: xDrip
theme: readthedocs
extra_css:
    - css/admonitions.css
    - css/extra.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁

#nav:
#    - 'Introduction': 'index.md'
